/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author reticent
 */
public class AdminModifyCourse extends javax.swing.JFrame {

    //Private Declared Memeber Variables
    Database db;    //Database db
    Object [] o;    //Holds course Information
    
    /**
     * Creates new form AdminModifyCourse
     */
    public AdminModifyCourse() {
        initComponents();
    }
    
    /**
     * AdminModifyCourse (Database db, Object [] o) Constructor
     * -------------------------------------------------------------------
     * Constructor that takes in Database information and Object [] o array
     * that contains information the selected row that is desired to be modified.
     * @param db
     * @param o 
     */
    public AdminModifyCourse(Database db, Object[]o) {
        this.db = db;
        this.o = o;
        initComponents();
        
        txtSectionNo.setText(Integer.toString((int)o[0]));
        txtCourseID.setText((String)o[1]);
        txtRoomNo.setText((String)o[2]);
        txtClassStartTime.setText(((Time)o[3]).toString());
        txtClassEndTime.setText(((Time)o[4]).toString());
        txtClassDays.setText((String)o[5]);
        txtStaffID.setText(Integer.toString((int)o[6]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSectionNo = new javax.swing.JLabel();
        txtSectionNo = new javax.swing.JTextField();
        lblCourseID = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        lblClassBeginTime = new javax.swing.JLabel();
        txtClassStartTime = new javax.swing.JTextField();
        lblRoomNo = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        lblCourseID1 = new javax.swing.JLabel();
        lblRoomNo1 = new javax.swing.JLabel();
        lblClassBeginTime1 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        txtClassDays = new javax.swing.JTextField();
        txtClassEndTime = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Courses");

        lblSectionNo.setText("Section No:");

        txtSectionNo.setEditable(false);

        lblCourseID.setText("Course ID:");

        lblClassBeginTime.setText("Class Start Time:");

        lblRoomNo.setText("Room No:");

        lblCourseID1.setText("Class End Time:");

        lblRoomNo1.setText("Class Days:");

        lblClassBeginTime1.setText("Staff ID:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSectionNo)
                    .addComponent(lblCourseID)
                    .addComponent(lblClassBeginTime)
                    .addComponent(lblRoomNo)
                    .addComponent(lblCourseID1)
                    .addComponent(lblRoomNo1)
                    .addComponent(lblClassBeginTime1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSectionNo)
                    .addComponent(txtCourseID)
                    .addComponent(txtClassStartTime, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtRoomNo)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtClassDays)
                    .addComponent(txtClassEndTime)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSectionNo)
                    .addComponent(txtSectionNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNo)
                    .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassBeginTime)
                    .addComponent(txtClassStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID1)
                    .addComponent(txtClassEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomNo1)
                    .addComponent(txtClassDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassBeginTime1)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * btnReset Action Performed
     * ----------------------------------
     * Reset JTxtFields to default setting.
     * @param evt 
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSectionNo.setText(Integer.toString((int)o[0]));
        txtCourseID.setText((String)o[1]);
        txtRoomNo.setText((String)o[2]);
        txtClassStartTime.setText(((Time)o[3]).toString());
        txtClassEndTime.setText(((Time)o[4]).toString());
        txtClassDays.setText((String)o[5]);
        txtStaffID.setText(Integer.toString((int)o[6]));
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * btnSubmit Action Performed
     * ----------------------------------------
     * Submits information through Object [] arr that calls upon Database function
     * updateCourseInfo(Object []) and sends that array in the following order.
     * o[0] = SectionNo
     * o[1] = CourseID
     * o[2] = RoomNo
     * o[3] = ClassStartTime
     * o[4] = ClassEndTime
     * o[5] = ClassDays
     * o[6] = StaffID
     * @param evt 
     */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //Instance Member Variables
        try
        {
            DateFormat formatter = new SimpleDateFormat("HH:mm");
            Object temp [];    //Holds changed info 
            int i = 0;  //Keeps track of any change
            int sectionNo = (int)o[0];  //Section Number
            String CourseID = txtCourseID.getText(); //Course ID
            String RoomNo = txtRoomNo.getText();   //Room Number
            Time classStartTime 
                    = new Time(formatter.
                            parse(txtClassStartTime.getText()).getTime()); //Class Start Time
            Time classEndTime 
                    = new Time(formatter.
                            parse(txtClassEndTime.getText()).getTime()); //Class End Time


            String classDays = txtClassDays.getText();    //Days Class in on
            int staffID = Integer.parseInt(txtStaffID.getText()) ;    //StaffID of Staff teaching class            
            
            if ( !(CourseID.equals((String)o[1])) )
            {
                i++;
            }
            
            if ( ! (RoomNo.equals((String)o[2])) )
            {
                i++;
            }
            
            if ( !(classStartTime.compareTo((Time)o[3])==0) )
            {
                i++;
            }
            
            if ( !(classEndTime.compareTo((Time)o[4])==0) )
            {
                i++;
            }
            
            if (!(classDays.equals((String)o[5])) )
            {
                i++;
            }
            
            if (!(staffID != (int)o[6]) )
            {
                i++;
            }
                
            
            if (i != 0) //If there are any changes
            {
                temp = new Object[7];
                temp[0] = sectionNo;
                temp[1] = CourseID;
                temp[2] = RoomNo;
                temp[3] = classStartTime;
                temp[4] = classEndTime;
                temp[5] = classDays;
                temp[6] = staffID;

                if(db.updateCourseInfo(temp)) //Update Student User Was Successful
                {
                    JOptionPane.showMessageDialog(null, "Update was successful.","Update Success",
                                        JOptionPane.DEFAULT_OPTION);
                    this.dispose();
                }
                else    //Update Student User Was Unsuccessful
                {
                    JOptionPane.showMessageDialog(null, "Update was unsuccessful.","Update Failed",
                                        JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                }
            }
        }
        catch (Exception e)
        {
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminModifyCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminModifyCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminModifyCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminModifyCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminModifyCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblClassBeginTime;
    private javax.swing.JLabel lblClassBeginTime1;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseID1;
    private javax.swing.JLabel lblRoomNo;
    private javax.swing.JLabel lblRoomNo1;
    private javax.swing.JLabel lblSectionNo;
    private javax.swing.JTextField txtClassDays;
    private javax.swing.JTextField txtClassEndTime;
    private javax.swing.JTextField txtClassStartTime;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtSectionNo;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
