/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author reticent
 */
public class ChangePasswordGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChangePasswordGUI
     */
    public ChangePasswordGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsername = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        pnlOriginalPwd = new javax.swing.JPanel();
        txtOldPwd = new javax.swing.JPasswordField();
        pnlNewPwd = new javax.swing.JPanel();
        txtNewPwd = new javax.swing.JPasswordField();
        pnlNewPwdAgain = new javax.swing.JPanel();
        txtNewPwdAgain = new javax.swing.JPasswordField();
        btnChangePwd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setResizable(false);

        pnlUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));

        javax.swing.GroupLayout pnlUsernameLayout = new javax.swing.GroupLayout(pnlUsername);
        pnlUsername.setLayout(pnlUsernameLayout);
        pnlUsernameLayout.setHorizontalGroup(
            pnlUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsernameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername)
                .addContainerGap())
        );
        pnlUsernameLayout.setVerticalGroup(
            pnlUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsernameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlOriginalPwd.setBorder(javax.swing.BorderFactory.createTitledBorder("Old Password"));

        javax.swing.GroupLayout pnlOriginalPwdLayout = new javax.swing.GroupLayout(pnlOriginalPwd);
        pnlOriginalPwd.setLayout(pnlOriginalPwdLayout);
        pnlOriginalPwdLayout.setHorizontalGroup(
            pnlOriginalPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOriginalPwdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOldPwd)
                .addContainerGap())
        );
        pnlOriginalPwdLayout.setVerticalGroup(
            pnlOriginalPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOriginalPwdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNewPwd.setBorder(javax.swing.BorderFactory.createTitledBorder("New Password"));

        javax.swing.GroupLayout pnlNewPwdLayout = new javax.swing.GroupLayout(pnlNewPwd);
        pnlNewPwd.setLayout(pnlNewPwdLayout);
        pnlNewPwdLayout.setHorizontalGroup(
            pnlNewPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPwdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewPwd)
                .addContainerGap())
        );
        pnlNewPwdLayout.setVerticalGroup(
            pnlNewPwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPwdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNewPwdAgain.setBorder(javax.swing.BorderFactory.createTitledBorder("Re-type New Password"));

        javax.swing.GroupLayout pnlNewPwdAgainLayout = new javax.swing.GroupLayout(pnlNewPwdAgain);
        pnlNewPwdAgain.setLayout(pnlNewPwdAgainLayout);
        pnlNewPwdAgainLayout.setHorizontalGroup(
            pnlNewPwdAgainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPwdAgainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewPwdAgain)
                .addContainerGap())
        );
        pnlNewPwdAgainLayout.setVerticalGroup(
            pnlNewPwdAgainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewPwdAgainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNewPwdAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnChangePwd.setText("Change Password");
        btnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePwdActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOriginalPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNewPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNewPwdAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChangePwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlOriginalPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNewPwdAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePwd)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * btnChangePwd Action Performed
     * ------------------------------------------
     * Changes password and salt of User if Username and Password are in the database.
     * @param evt 
     */
    private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePwdActionPerformed
        
        //Instanced Variable
        Database db = new Database();   //Database
        String username = txtUsername.getText();    //Username
        char [] oldPwd = txtOldPwd.getPassword();   //Old Password
        char [] newPwd = txtNewPwd.getPassword();   //New Password
        char [] newPwdAgain = txtNewPwdAgain.getPassword(); //Reconfimation of New Password
        
        try
        {
            if (username.equals("") || oldPwd.length == 0 || newPwd.length == 0 || newPwdAgain.length == 0)
            {
                JOptionPane.showMessageDialog(null, "Missing Fields","Change Password Failed",
                                            JOptionPane.ERROR_MESSAGE);
            }
            else if (db.checkLogin(username, oldPwd)) //If User Login info is correct
            {


                if (Arrays.equals(newPwd, newPwdAgain)) //If newPwd and newPwdAgain match up
                {
                    db.changeUserPwd(username, newPwd);
                    JOptionPane.showMessageDialog(null, "Password Changed!"
                                            ,"Password Change Successful", JOptionPane.DEFAULT_OPTION);
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect Login Information"
                                            ,"Change Password Failed", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect Login Information","Change Password Failed",
                                            JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e)
        {
            System.out.println("Error chaning password (GUI): " + e);
        }
        
    }//GEN-LAST:event_btnChangePwdActionPerformed

    /**
     * btnExit Action Performed
     * -----------------------------------------
     * Disposes of GUI.
     * @param evt 
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePwd;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel pnlNewPwd;
    private javax.swing.JPanel pnlNewPwdAgain;
    private javax.swing.JPanel pnlOriginalPwd;
    private javax.swing.JPanel pnlUsername;
    private javax.swing.JPasswordField txtNewPwd;
    private javax.swing.JPasswordField txtNewPwdAgain;
    private javax.swing.JPasswordField txtOldPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
