/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seproject;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reticent
 */
public class StaffGUI extends javax.swing.JFrame {
    
    //Declared Member Variables
    private Staff user;  //Holds User class of current User
    private Database db;

    /**
     * Creates new form StaffGUI
     */
    public StaffGUI() {
        db = new Database();
        initComponents();
    }

    /**
     * StaffGUI(User user, Database db)
     * ------------------------------
     * StaffUI Constructor with 2 constructor.
     * @param user 
     */
    public StaffGUI(User user, Database db) {
        initComponents();
        this.user = (Staff)user;
        this.db = db;
        
        if (this.user.getPosition().equals("Database Administrator"))
        {
            btnAdminManage.setVisible(true);
        }
        else
        {
            btnAdminManage.setVisible(false);
        }
        
        fillCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdStaff = new javax.swing.JTabbedPane();
        pnlManageClasses = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMngClasses = new javax.swing.JTable();
        btnAdminManage = new javax.swing.JButton();
        pnlViewStudents = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        pnlManageAssignments = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMS Staff GUI");
        setResizable(false);

        tblMngClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Section No.", "Course ID", "Room No.", "Begin Time", "End Time", "Class Days", "Staff ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMngClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMngClassesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMngClasses);

        btnAdminManage.setText("Admin Only");
        btnAdminManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManageClassesLayout = new javax.swing.GroupLayout(pnlManageClasses);
        pnlManageClasses.setLayout(pnlManageClassesLayout);
        pnlManageClassesLayout.setHorizontalGroup(
            pnlManageClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageClassesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminManage)
                .addContainerGap())
            .addGroup(pnlManageClassesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlManageClassesLayout.setVerticalGroup(
            pnlManageClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAdminManage)
                .addContainerGap())
        );

        tbdStaff.addTab("Manage Classes", pnlManageClasses);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID ", "First Name", "Last Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudents);

        javax.swing.GroupLayout pnlViewStudentsLayout = new javax.swing.GroupLayout(pnlViewStudents);
        pnlViewStudents.setLayout(pnlViewStudentsLayout);
        pnlViewStudentsLayout.setHorizontalGroup(
            pnlViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        pnlViewStudentsLayout.setVerticalGroup(
            pnlViewStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tbdStaff.addTab("View Students", pnlViewStudents);

        javax.swing.GroupLayout pnlManageAssignmentsLayout = new javax.swing.GroupLayout(pnlManageAssignments);
        pnlManageAssignments.setLayout(pnlManageAssignmentsLayout);
        pnlManageAssignmentsLayout.setHorizontalGroup(
            pnlManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1168, Short.MAX_VALUE)
        );
        pnlManageAssignmentsLayout.setVerticalGroup(
            pnlManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        tbdStaff.addTab("Manage Assignments", pnlManageAssignments);

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdStaff)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbdStaff)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminManageActionPerformed
        AdminGUI gui = new AdminGUI(this,db);
        gui.setVisible(true);
    }//GEN-LAST:event_btnAdminManageActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        LoginMenu gui = new LoginMenu();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblMngClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMngClassesMouseClicked
        try
        {
            //Instanced Variables
            JTable tbl = (JTable)evt.getSource();
            Object temp = tbl.getValueAt(tbl.getSelectedRow(), 0);
            int courseID = (int) temp;

            ArrayList<ArrayList<Object>> s = db.getStudentInfoInCourse(courseID);
            int size = s.size();
            
            if (size != 0)
            {
                DefaultTableModel model = (DefaultTableModel)tblStudents.getModel();
                model.setRowCount(0); //Reset Table to 0
                
                for (int x = 0; x < size; x++)
                {
                    model.addRow(new Object[]{s.get(x).get(0),s.get(x).get(1),s.get(x).get(2)} );
                }
                
                tbdStaff.setSelectedIndex(1);
            }
            else    //if empty
            {
                DefaultTableModel model = (DefaultTableModel)tblStudents.getModel();
                model.setRowCount(0); //Reset Table to 0
                tbdStaff.setSelectedIndex(1);
            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblMngClassesMouseClicked

    
    private void fillCourses()
    {
        try
        {
            if (user.getPosition().equals("Database Administrator"))    //Staff is Admin
            {
                //Instanced Variables
                ArrayList<ArrayList<Object>> o = db.getAllCourses();   //Stores each User from DB
                DefaultTableModel model = (DefaultTableModel)tblMngClasses.getModel();
                model.setRowCount(0); //Reset Table to 0

                for (int x = 0; x < o.size(); x++)
                {
                    int size = o.get(x).size();

                    model.addRow(new Object[]{o.get(x).get(0),o.get(x).get(1),o.get(x).get(2),o.get(x).get(3), o.get(x).get(4), o.get(x).get(5),o.get(x).get(6)} );

                }
            }
            else    //Staff is a teacher
            {
                //Instanced Variables
                ArrayList<ArrayList<Object>> o = db.getCourseTaughtByTeacher(user.getId());   //Stores each User from DB
                DefaultTableModel model = (DefaultTableModel)tblMngClasses.getModel();
                model.setRowCount(0); //Reset Table to 0

                for (int x = 0; x < o.size(); x++)
                {
                    int size = o.get(x).size();

                    model.addRow(new Object[]{o.get(x).get(0),o.get(x).get(1),o.get(x).get(2),o.get(x).get(3), o.get(x).get(4), o.get(x).get(5),o.get(x).get(6)} );

                }
            }
        }
        catch (Exception e)
        {
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminManage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlManageAssignments;
    private javax.swing.JPanel pnlManageClasses;
    private javax.swing.JPanel pnlViewStudents;
    private javax.swing.JTabbedPane tbdStaff;
    private javax.swing.JTable tblMngClasses;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
